project_id = "ghuiotbjwefwwguvzphe"

[functions.customer-me]
verify_jwt = false

[functions.customer-upsert]
verify_jwt = false

[functions.spin]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.customer-auth]
verify_jwt = false

[functions.order-api]
verify_jwt = false
