-- Car ordering, WhatsApp customer login, menu management, and order analytics.
-- Customer-facing writes are performed through Edge Functions using service_role.
-- Staff reads are tenant-isolated with RLS; state changes go through guarded RPCs.

alter table public.cafes
  add column if not exists car_ordering_enabled boolean not null default true,
  add column if not exists customer_login_required boolean not null default false,
  add column if not exists order_min_total numeric(10,2) not null default 0;

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, cafe_id)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  category_id uuid,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  description text,
  image_url text,
  base_price numeric(10,2) not null check (base_price >= 0),
  preparation_minutes integer not null default 10 check (preparation_minutes between 0 and 240),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, cafe_id),
  constraint products_category_cafe_fkey
    foreign key (category_id, cafe_id)
    references public.product_categories(id, cafe_id)
    on delete restrict
);

create table if not exists public.product_options (
  id uuid primary key default gen_random_uuid(),
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  product_id uuid not null,
  group_name text not null default 'الإضافات'
    check (char_length(btrim(group_name)) between 1 and 80),
  name text not null check (char_length(btrim(name)) between 1 and 100),
  price_delta numeric(10,2) not null default 0 check (price_delta >= 0),
  is_multiple boolean not null default true,
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, cafe_id),
  constraint product_options_product_cafe_fkey
    foreign key (product_id, cafe_id)
    references public.products(id, cafe_id)
    on delete cascade
);

create table if not exists public.customer_login_challenges (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  code_hash text not null check (char_length(code_hash) = 64),
  attempts integer not null default 0 check (attempts between 0 and 5),
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_sessions (
  token_hash text primary key check (char_length(token_hash) = 64),
  customer_id uuid not null references public.customers(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending','accepted','preparing','ready','completed','cancelled','no_show')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid','paid','void')),
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  discount_total numeric(10,2) not null default 0 check (discount_total >= 0),
  total numeric(10,2) not null default 0 check (total >= 0),
  reward_id uuid references public.rewards(id) on delete set null,
  visit_id uuid unique references public.visits(id) on delete set null,
  vehicle_plate text not null check (char_length(btrim(vehicle_plate)) between 2 and 30),
  vehicle_color text not null check (char_length(btrim(vehicle_color)) between 2 and 40),
  vehicle_model text,
  parking_spot text,
  note text,
  accepted_at timestamptz,
  preparing_at timestamptz,
  ready_at timestamptz,
  arrived_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  base_unit_price numeric(10,2) not null check (base_unit_price >= 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 50),
  line_total numeric(10,2) not null check (line_total >= 0),
  reward_applied boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.order_item_options (
  id uuid primary key default gen_random_uuid(),
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  option_id uuid references public.product_options(id) on delete set null,
  option_name text not null,
  price_delta numeric(10,2) not null check (price_delta >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  status text not null,
  changed_by uuid references public.staff(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_reservations (
  id uuid primary key default gen_random_uuid(),
  cafe_id uuid not null references public.cafes(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  reward_id uuid not null references public.rewards(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  consumed_at timestamptz,
  released_at timestamptz
);

create unique index if not exists product_categories_cafe_name_key
  on public.product_categories(cafe_id, lower(name));
create index if not exists product_categories_cafe_order_idx
  on public.product_categories(cafe_id, is_active, sort_order);
create index if not exists products_category_cafe_idx on public.products(category_id, cafe_id);
create index if not exists products_cafe_menu_idx
  on public.products(cafe_id, is_active, is_available, sort_order);
create index if not exists product_options_product_cafe_idx on public.product_options(product_id, cafe_id);
create index if not exists product_options_cafe_product_idx
  on public.product_options(cafe_id, product_id, is_active, sort_order);
create index if not exists customer_login_challenges_customer_recent_idx
  on public.customer_login_challenges(customer_id, requested_at desc);
create index if not exists customer_sessions_customer_idx on public.customer_sessions(customer_id);
create index if not exists customer_sessions_active_idx
  on public.customer_sessions(expires_at) where revoked_at is null;
create index if not exists orders_customer_created_idx
  on public.orders(customer_id, created_at desc);
create index if not exists orders_cafe_status_created_idx
  on public.orders(cafe_id, status, created_at desc);
create index if not exists orders_cafe_active_idx
  on public.orders(cafe_id, created_at desc)
  where status in ('pending','accepted','preparing','ready');
create index if not exists orders_reward_id_idx on public.orders(reward_id);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_product_id_idx on public.order_items(product_id);
create index if not exists order_items_cafe_product_idx on public.order_items(cafe_id, product_id);
create index if not exists order_item_options_item_id_idx on public.order_item_options(order_item_id);
create index if not exists order_item_options_cafe_id_idx on public.order_item_options(cafe_id);
create index if not exists order_item_options_option_id_idx on public.order_item_options(option_id);
create index if not exists order_status_history_order_idx
  on public.order_status_history(order_id, created_at desc);
create index if not exists order_status_history_cafe_id_idx on public.order_status_history(cafe_id);
create index if not exists order_status_history_changed_by_idx on public.order_status_history(changed_by);
create index if not exists reward_reservations_customer_idx on public.reward_reservations(customer_id);
create index if not exists reward_reservations_cafe_id_idx on public.reward_reservations(cafe_id);
create unique index if not exists reward_reservations_active_reward_key
  on public.reward_reservations(reward_id)
  where consumed_at is null and released_at is null;
create unique index if not exists reward_reservations_active_order_key
  on public.reward_reservations(order_id)
  where consumed_at is null and released_at is null;

drop trigger if exists product_categories_touch_updated_at on public.product_categories;
create trigger product_categories_touch_updated_at before update on public.product_categories
for each row execute function public.touch_updated_at();
drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products
for each row execute function public.touch_updated_at();
drop trigger if exists product_options_touch_updated_at on public.product_options;
create trigger product_options_touch_updated_at before update on public.product_options
for each row execute function public.touch_updated_at();
drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
for each row execute function public.touch_updated_at();

alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.product_options enable row level security;
alter table public.customer_login_challenges enable row level security;
alter table public.customer_sessions enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_item_options enable row level security;
alter table public.order_status_history enable row level security;
alter table public.reward_reservations enable row level security;

drop policy if exists product_categories_staff_read on public.product_categories;
create policy product_categories_staff_read on public.product_categories
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists product_categories_owner_insert on public.product_categories;
create policy product_categories_owner_insert on public.product_categories
for insert to authenticated with check ((select public.is_owner_of(cafe_id)));
drop policy if exists product_categories_owner_update on public.product_categories;
create policy product_categories_owner_update on public.product_categories
for update to authenticated
using ((select public.is_owner_of(cafe_id))) with check ((select public.is_owner_of(cafe_id)));
drop policy if exists product_categories_owner_delete on public.product_categories;
create policy product_categories_owner_delete on public.product_categories
for delete to authenticated using ((select public.is_owner_of(cafe_id)));

drop policy if exists products_staff_read on public.products;
create policy products_staff_read on public.products
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists products_owner_insert on public.products;
create policy products_owner_insert on public.products
for insert to authenticated with check ((select public.is_owner_of(cafe_id)));
drop policy if exists products_owner_update on public.products;
create policy products_owner_update on public.products
for update to authenticated
using ((select public.is_owner_of(cafe_id))) with check ((select public.is_owner_of(cafe_id)));
drop policy if exists products_owner_delete on public.products;
create policy products_owner_delete on public.products
for delete to authenticated using ((select public.is_owner_of(cafe_id)));

drop policy if exists product_options_staff_read on public.product_options;
create policy product_options_staff_read on public.product_options
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists product_options_owner_insert on public.product_options;
create policy product_options_owner_insert on public.product_options
for insert to authenticated with check ((select public.is_owner_of(cafe_id)));
drop policy if exists product_options_owner_update on public.product_options;
create policy product_options_owner_update on public.product_options
for update to authenticated
using ((select public.is_owner_of(cafe_id))) with check ((select public.is_owner_of(cafe_id)));
drop policy if exists product_options_owner_delete on public.product_options;
create policy product_options_owner_delete on public.product_options
for delete to authenticated using ((select public.is_owner_of(cafe_id)));

drop policy if exists orders_staff_read on public.orders;
create policy orders_staff_read on public.orders
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists order_items_staff_read on public.order_items;
create policy order_items_staff_read on public.order_items
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists order_item_options_staff_read on public.order_item_options;
create policy order_item_options_staff_read on public.order_item_options
for select to authenticated using ((select public.is_staff_of(cafe_id)));
drop policy if exists order_status_history_staff_read on public.order_status_history;
create policy order_status_history_staff_read on public.order_status_history
for select to authenticated using ((select public.is_staff_of(cafe_id)));

revoke all on public.customer_login_challenges, public.customer_sessions,
  public.reward_reservations from public, anon, authenticated;
grant all on public.customer_login_challenges, public.customer_sessions,
  public.reward_reservations to service_role;

grant select, insert, update, delete on public.product_categories,
  public.products, public.product_options to authenticated, service_role;
grant select on public.orders, public.order_items, public.order_item_options,
  public.order_status_history to authenticated;
grant all on public.orders, public.order_items, public.order_item_options,
  public.order_status_history to service_role;
grant usage, select on sequence public.orders_order_number_seq to service_role;
grant usage, select on sequence public.order_status_history_id_seq to service_role;
grant select on sequence public.orders_order_number_seq to authenticated;

create or replace function public.verify_customer_login(
  p_challenge uuid,
  p_code_hash text,
  p_session_hash text,
  p_session_expires_at timestamptz
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_challenge public.customer_login_challenges%rowtype;
begin
  if p_session_expires_at <= pg_catalog.now()
     or p_session_expires_at > pg_catalog.now() + interval '31 days' then
    raise exception 'INVALID_SESSION_EXPIRY';
  end if;

  select * into v_challenge
  from public.customer_login_challenges
  where id = p_challenge
  for update;

  if not found or v_challenge.used_at is not null then
    return jsonb_build_object('error', 'INVALID_CHALLENGE');
  end if;
  if v_challenge.expires_at <= pg_catalog.now() then
    return jsonb_build_object('error', 'OTP_EXPIRED');
  end if;
  if v_challenge.attempts >= 5 then
    return jsonb_build_object('error', 'OTP_LOCKED');
  end if;
  if v_challenge.code_hash <> p_code_hash then
    update public.customer_login_challenges
      set attempts = least(attempts + 1, 5)
      where id = p_challenge;
    return jsonb_build_object(
      'error', case when v_challenge.attempts + 1 >= 5 then 'OTP_LOCKED' else 'OTP_INVALID' end,
      'attempts_remaining', greatest(5 - (v_challenge.attempts + 1), 0)
    );
  end if;

  update public.customer_login_challenges
    set used_at = pg_catalog.now()
    where id = p_challenge;

  insert into public.customer_sessions(token_hash, customer_id, expires_at)
  values (p_session_hash, v_challenge.customer_id, p_session_expires_at);

  update public.customers
    set verified_at = coalesce(verified_at, pg_catalog.now()),
        verify_attempts = 0,
        verify_locked_until = null
    where id = v_challenge.customer_id;

  return jsonb_build_object(
    'customer_id', v_challenge.customer_id,
    'expires_at', p_session_expires_at
  );
end
$function$;

create or replace function public.create_car_order(
  p_customer uuid,
  p_vehicle_plate text,
  p_vehicle_color text,
  p_vehicle_model text,
  p_note text,
  p_items jsonb,
  p_reward uuid default null,
  p_reward_product uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_cafe uuid;
  v_enabled boolean;
  v_min_total numeric(10,2);
  v_order uuid;
  v_order_number bigint;
  v_item jsonb;
  v_product public.products%rowtype;
  v_item_id uuid;
  v_qty integer;
  v_option_ids uuid[];
  v_option_count integer;
  v_option_sum numeric(10,2);
  v_unit numeric(10,2);
  v_subtotal numeric(10,2) := 0;
  v_discount numeric(10,2) := 0;
  v_reward public.rewards%rowtype;
begin
  if jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) < 1
     or jsonb_array_length(p_items) > 50 then
    raise exception 'INVALID_ITEMS';
  end if;
  if char_length(btrim(coalesce(p_vehicle_plate, ''))) not between 2 and 30
     or char_length(btrim(coalesce(p_vehicle_color, ''))) not between 2 and 40 then
    raise exception 'INVALID_VEHICLE';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_customer::text, 7));
  select c.cafe_id, f.car_ordering_enabled, f.order_min_total
    into v_cafe, v_enabled, v_min_total
  from public.customers c
  join public.cafes f on f.id = c.cafe_id and f.is_active = true
  where c.id = p_customer
  for share of c, f;
  if not found then raise exception 'CUSTOMER_NOT_FOUND'; end if;
  if not v_enabled then raise exception 'ORDERING_DISABLED'; end if;

  if exists (
    select 1 from public.orders o
    where o.customer_id = p_customer
      and o.status in ('pending','accepted','preparing','ready')
  ) then raise exception 'ACTIVE_ORDER_EXISTS'; end if;

  insert into public.orders(
    cafe_id, customer_id, vehicle_plate, vehicle_color, vehicle_model, note
  ) values (
    v_cafe, p_customer, upper(left(btrim(p_vehicle_plate), 30)),
    left(btrim(p_vehicle_color), 40), nullif(left(btrim(p_vehicle_model), 80), ''),
    nullif(left(btrim(p_note), 500), '')
  ) returning id, order_number into v_order, v_order_number;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_qty := coalesce((v_item->>'quantity')::integer, 0);
    if v_qty < 1 or v_qty > 50 then raise exception 'INVALID_QUANTITY'; end if;

    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid
      and cafe_id = v_cafe and is_active = true and is_available = true
    for share;
    if not found then raise exception 'PRODUCT_UNAVAILABLE'; end if;

    select coalesce(array_agg(distinct value::uuid), '{}'::uuid[])
      into v_option_ids
    from jsonb_array_elements_text(coalesce(v_item->'option_ids', '[]'::jsonb));

    select count(*)::integer, coalesce(sum(o.price_delta), 0)::numeric(10,2)
      into v_option_count, v_option_sum
    from public.product_options o
    where o.id = any(v_option_ids)
      and o.product_id = v_product.id and o.cafe_id = v_cafe and o.is_active = true;
    if v_option_count <> coalesce(array_length(v_option_ids, 1), 0) then
      raise exception 'INVALID_OPTIONS';
    end if;
    if exists (
      select 1 from public.product_options o
      where o.id = any(v_option_ids)
      group by o.group_name
      having count(*) filter (where o.is_multiple = false) > 0 and count(*) > 1
    ) then raise exception 'INVALID_OPTIONS'; end if;

    v_unit := v_product.base_price + v_option_sum;
    insert into public.order_items(
      order_id, cafe_id, product_id, product_name, base_unit_price,
      unit_price, quantity, line_total
    ) values (
      v_order, v_cafe, v_product.id, v_product.name, v_product.base_price,
      v_unit, v_qty, v_unit * v_qty
    ) returning id into v_item_id;

    insert into public.order_item_options(
      order_item_id, cafe_id, option_id, option_name, price_delta
    )
    select v_item_id, v_cafe, o.id, o.name, o.price_delta
    from public.product_options o
    where o.id = any(v_option_ids)
    order by o.sort_order, o.id;

    v_subtotal := v_subtotal + (v_unit * v_qty);
  end loop;

  if v_subtotal < coalesce(v_min_total, 0) then raise exception 'MIN_TOTAL_NOT_MET'; end if;

  if p_reward is not null then
    select * into v_reward from public.rewards
    where id = p_reward and customer_id = p_customer and cafe_id = v_cafe
    for update;
    if not found or v_reward.status <> 'available'
       or (v_reward.expires_at is not null and v_reward.expires_at <= pg_catalog.now())
       or v_reward.reward_type <> 'free_cup' then
      raise exception 'REWARD_NOT_AVAILABLE';
    end if;
    if p_reward_product is null then raise exception 'REWARD_PRODUCT_REQUIRED'; end if;
    if exists (
      select 1 from public.reward_reservations r
      where r.reward_id = p_reward and r.consumed_at is null and r.released_at is null
    ) then raise exception 'REWARD_RESERVED'; end if;

    -- The free-cup reward covers exactly one product base price. Options remain payable.
    select least(oi.base_unit_price, v_subtotal) into v_discount
    from public.order_items oi
    where oi.order_id = v_order and oi.product_id = p_reward_product
    order by oi.created_at, oi.id limit 1;
    if v_discount is null then raise exception 'REWARD_PRODUCT_NOT_IN_ORDER'; end if;

    update public.order_items set reward_applied = true
    where id = (
      select oi.id from public.order_items oi
      where oi.order_id = v_order and oi.product_id = p_reward_product
      order by oi.created_at, oi.id limit 1
    );

    update public.orders set reward_id = p_reward where id = v_order;
    insert into public.reward_reservations(cafe_id, customer_id, reward_id, order_id)
    values (v_cafe, p_customer, p_reward, v_order);
  end if;

  update public.orders
    set subtotal = v_subtotal, discount_total = v_discount,
        total = greatest(v_subtotal - v_discount, 0)
    where id = v_order;

  insert into public.order_status_history(order_id, cafe_id, status)
  values (v_order, v_cafe, 'pending');

  return jsonb_build_object(
    'order_id', v_order,
    'order_number', v_order_number,
    'subtotal', v_subtotal,
    'discount_total', v_discount,
    'total', greatest(v_subtotal - v_discount, 0)
  );
end
$function$;

create or replace function public.customer_mark_order_arrived(
  p_customer uuid,
  p_order uuid,
  p_parking_spot text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order from public.orders
  where id = p_order and customer_id = p_customer
  for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_order.status not in ('pending','accepted','preparing','ready') then
    raise exception 'ORDER_NOT_ACTIVE';
  end if;
  update public.orders
    set arrived_at = coalesce(arrived_at, pg_catalog.now()),
        parking_spot = nullif(left(btrim(p_parking_spot), 50), '')
    where id = p_order;
  return jsonb_build_object('order_id', p_order, 'arrived_at', coalesce(v_order.arrived_at, pg_catalog.now()));
end
$function$;

create or replace function public.customer_cancel_car_order(
  p_customer uuid,
  p_order uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_cafe uuid;
begin
  select cafe_id into v_cafe from public.orders
  where id = p_order and customer_id = p_customer and status = 'pending'
  for update;
  if not found then raise exception 'ORDER_CANNOT_BE_CANCELLED'; end if;
  update public.orders set status = 'cancelled', payment_status = 'void',
    cancelled_at = pg_catalog.now() where id = p_order;
  update public.reward_reservations set released_at = pg_catalog.now()
    where order_id = p_order and consumed_at is null and released_at is null;
  insert into public.order_status_history(order_id, cafe_id, status, note)
  values (p_order, v_cafe, 'cancelled', 'ألغاه العميل');
  return jsonb_build_object('order_id', p_order, 'status', 'cancelled');
end
$function$;

create or replace function public.staff_update_car_order(
  p_order uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_order public.orders%rowtype;
  v_staff uuid;
begin
  if (select auth.uid()) is null then raise exception 'UNAUTHENTICATED'; end if;
  select * into v_order from public.orders where id = p_order for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if not public.is_staff_of(v_order.cafe_id) then raise exception 'NOT_AUTHORIZED'; end if;
  select s.id into v_staff from public.staff s
  where s.user_id = (select auth.uid()) and s.cafe_id = v_order.cafe_id and s.is_active = true
  limit 1;

  if not (
    (v_order.status = 'pending' and p_status in ('accepted','cancelled')) or
    (v_order.status = 'accepted' and p_status in ('preparing','ready','cancelled')) or
    (v_order.status = 'preparing' and p_status in ('ready','cancelled')) or
    (v_order.status = 'ready' and p_status in ('cancelled','no_show'))
  ) then raise exception 'INVALID_STATUS_TRANSITION'; end if;

  update public.orders set
    status = p_status,
    accepted_at = case when p_status = 'accepted' then pg_catalog.now() else accepted_at end,
    preparing_at = case when p_status = 'preparing' then pg_catalog.now() else preparing_at end,
    ready_at = case when p_status = 'ready' then pg_catalog.now() else ready_at end,
    cancelled_at = case when p_status in ('cancelled','no_show') then pg_catalog.now() else cancelled_at end,
    payment_status = case when p_status in ('cancelled','no_show') then 'void' else payment_status end
  where id = p_order;

  if p_status in ('cancelled','no_show') then
    update public.reward_reservations set released_at = pg_catalog.now()
    where order_id = p_order and consumed_at is null and released_at is null;
  end if;
  insert into public.order_status_history(order_id, cafe_id, status, changed_by)
  values (p_order, v_order.cafe_id, p_status, v_staff);
  return jsonb_build_object('order_id', p_order, 'status', p_status);
end
$function$;

create or replace function public.complete_car_order(p_order uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_order public.orders%rowtype;
  v_staff uuid;
  v_visit_result jsonb;
  v_visit uuid;
begin
  if (select auth.uid()) is null then raise exception 'UNAUTHENTICATED'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_order::text, 11));
  select * into v_order from public.orders where id = p_order for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if not public.is_staff_of(v_order.cafe_id) then raise exception 'NOT_AUTHORIZED'; end if;
  if v_order.status not in ('accepted','preparing','ready') then
    raise exception 'ORDER_NOT_READY';
  end if;
  select s.id into v_staff from public.staff s
  where s.user_id = (select auth.uid()) and s.cafe_id = v_order.cafe_id and s.is_active = true
  limit 1;

  if v_order.reward_id is not null then
    update public.rewards set status = 'used', used_at = pg_catalog.now(), used_by_staff = v_staff
    where id = v_order.reward_id and customer_id = v_order.customer_id and status = 'available';
    if not found then raise exception 'REWARD_NOT_AVAILABLE'; end if;
    update public.reward_reservations set consumed_at = pg_catalog.now()
    where order_id = p_order and reward_id = v_order.reward_id
      and consumed_at is null and released_at is null;
  end if;

  if v_order.total > 0 then
    v_visit_result := public.add_visit(
      v_order.customer_id, 1, null,
      'طلب سيارة #' || v_order.order_number::text
    );
    v_visit := (v_visit_result->>'visit_id')::uuid;
  end if;

  update public.orders set status = 'completed', payment_status = 'paid',
    completed_at = pg_catalog.now(), visit_id = v_visit
  where id = p_order;
  insert into public.order_status_history(order_id, cafe_id, status, changed_by)
  values (p_order, v_order.cafe_id, 'completed', v_staff);

  return jsonb_build_object(
    'order_id', p_order,
    'status', 'completed',
    'visit_id', v_visit,
    'loyalty', v_visit_result
  );
end
$function$;

-- Manual redemption must not consume a reward already reserved by a car order.
create or replace function public.redeem_reward(p_reward uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_reward public.rewards%rowtype;
  v_staff uuid;
begin
  select * into v_reward from public.rewards where id = p_reward for update;
  if not found then raise exception 'REWARD_NOT_FOUND'; end if;
  if not public.is_staff_of(v_reward.cafe_id) then raise exception 'NOT_AUTHORIZED'; end if;
  if v_reward.status <> 'available' then raise exception 'REWARD_NOT_AVAILABLE'; end if;
  if exists (
    select 1 from public.reward_reservations r
    where r.reward_id = p_reward and r.consumed_at is null and r.released_at is null
  ) then raise exception 'REWARD_RESERVED'; end if;

  if v_reward.expires_at is not null and v_reward.expires_at < pg_catalog.now() then
    update public.rewards set status = 'expired' where id = p_reward;
    return jsonb_build_object('reward_id', p_reward, 'status', 'expired');
  end if;
  select s.id into v_staff from public.staff s
  where s.user_id = (select auth.uid()) and s.cafe_id = v_reward.cafe_id
    and s.is_active = true limit 1;
  update public.rewards set status = 'used', used_at = pg_catalog.now(), used_by_staff = v_staff
  where id = p_reward and status = 'available';
  if not found then raise exception 'REWARD_NOT_AVAILABLE'; end if;
  return jsonb_build_object('reward_id', p_reward, 'status', 'used');
end
$function$;

create or replace function public.order_report_overview(
  p_cafe uuid,
  p_from timestamptz,
  p_to timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_result jsonb;
begin
  if (select auth.uid()) is null or not public.is_owner_of(p_cafe) then
    raise exception 'NOT_AUTHORIZED';
  end if;
  if p_from is null or p_to is null or p_from > p_to
     or p_to - p_from > interval '370 days' then
    raise exception 'INVALID_RANGE';
  end if;

  select jsonb_build_object(
    'totals', jsonb_build_object(
      'orders', count(*),
      'completed', count(*) filter (where o.status = 'completed'),
      'cancelled', count(*) filter (where o.status in ('cancelled','no_show')),
      'active', count(*) filter (where o.status in ('pending','accepted','preparing','ready')),
      'revenue', coalesce(sum(o.total) filter (where o.status = 'completed'), 0),
      'avg_prep_minutes', coalesce(round(avg(extract(epoch from (o.ready_at - o.accepted_at))/60)
        filter (where o.ready_at is not null and o.accepted_at is not null), 1), 0),
      'avg_arrival_wait_minutes', coalesce(round(avg(extract(epoch from (o.completed_at - o.arrived_at))/60)
        filter (where o.completed_at is not null and o.arrived_at is not null), 1), 0)
    ),
    'products', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'name', x.product_name, 'quantity', x.quantity, 'revenue', x.revenue
      ) order by x.quantity desc, x.product_name), '[]'::jsonb)
      from (
        select oi.product_name, sum(oi.quantity)::integer quantity,
          sum(oi.line_total - case when oi.reward_applied then po.discount_total else 0 end)::numeric(12,2) revenue
        from public.order_items oi
        join public.orders po on po.id = oi.order_id
        where po.cafe_id = p_cafe and po.status = 'completed'
          and po.created_at between p_from and p_to
        group by oi.product_name
      ) x
    ),
    'by_hour', (
      select coalesce(jsonb_agg(jsonb_build_object('hour', x.hour_value, 'orders', x.orders)
        order by x.hour_value), '[]'::jsonb)
      from (
        select extract(hour from o2.created_at at time zone 'Asia/Riyadh')::integer as hour_value,
          count(*)::integer orders
        from public.orders o2
        where o2.cafe_id = p_cafe and o2.created_at between p_from and p_to
        group by 1
      ) x
    )
  ) into v_result
  from public.orders o
  where o.cafe_id = p_cafe and o.created_at between p_from and p_to;
  return v_result;
end
$function$;

revoke execute on function public.verify_customer_login(uuid,text,text,timestamptz) from public, anon, authenticated;
revoke execute on function public.create_car_order(uuid,text,text,text,text,jsonb,uuid,uuid) from public, anon, authenticated;
revoke execute on function public.customer_mark_order_arrived(uuid,uuid,text) from public, anon, authenticated;
revoke execute on function public.customer_cancel_car_order(uuid,uuid) from public, anon, authenticated;
revoke execute on function public.staff_update_car_order(uuid,text) from public, anon;
revoke execute on function public.complete_car_order(uuid) from public, anon;
revoke execute on function public.order_report_overview(uuid,timestamptz,timestamptz) from public, anon;

grant execute on function public.verify_customer_login(uuid,text,text,timestamptz) to service_role;
grant execute on function public.create_car_order(uuid,text,text,text,text,jsonb,uuid,uuid) to service_role;
grant execute on function public.customer_mark_order_arrived(uuid,uuid,text) to service_role;
grant execute on function public.customer_cancel_car_order(uuid,uuid) to service_role;
grant execute on function public.staff_update_car_order(uuid,text) to authenticated, service_role;
grant execute on function public.complete_car_order(uuid) to authenticated, service_role;
grant execute on function public.order_report_overview(uuid,timestamptz,timestamptz) to authenticated, service_role;

do $do$
begin
  if not exists (
    select 1 from pg_catalog.pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end
$do$;
